[tool.poetry]
name = "fastapi-health-monitor"
version = "1.0.1"
description = "A health monitor for FastAPI applications."
authors = ["Adam Kirchberger <adamkirchberger@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "fastapi_health_monitor"}]

classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Framework :: FastAPI",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.101.0"
httpx = "^0.24.1"
pydantic = "^2.1.1"
pydantic-settings = "^2.0.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
uvicorn = "^0.23.2"
pylint = "^2.17.5"
pytest-cov = "^4.1.0"
pytest-forked = "^1.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.'MESSAGES CONTROL']
disable = "C0301,C0114,C0115,W1203,R0902,R0914,C0103,R0913,R0903"

[tool.pytest.ini_options]
addopts = "--cov=fastapi_health_monitor --cov-report term-missing --forked -vv"

[tool.semantic_release]
version_variables = [
    "fastapi_health_monitor/__init__.py:__version__"
]
version_toml = [
    "pyproject.toml:tool.poetry.version"
]
tag_format = "{version}"
commit_message = "Automatically generated by python-semantic-release"
branch = "main"
build_command = "pip install poetry && poetry build --format sdist"
commit_author = "github-actions <action@github.com>"

[tool.semantic_release.publish]
upload_to_vcs_release = false
